- name: print variables from inventory
  hosts: local
  connection: local
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "name is {{ myname }},country is {{ mycountry }}"
