- name: Devops course info
  hosts: local
  connection: local
  vars:
    course_name: "Devops with AWS" # string
    course_duration: 6 # integer
    course_price: 499.99 # float
    course_topics: # list
      - Ansible
      - Docker
      - Kubernetes
    course_details: # dictionary
      ci: jenkins
      cd: gitlab
      live_project: true # boolean
  tasks:
  - name: display course info
    ansible.builtin.debug:
      msg: "Course Name: {{ course_name }}, Duration: {{ course_duration }} weeks, Price: ${{ course_price }}, Topics: {{ course_topics }}, Details: {{ course_details }}"
      



